const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Chao: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Piscar: 0},
	{Jogador: 0},
	{plataforma: 0},
	{PortaSaida: 0},
	{portaentrada: 0},
	{Sprite: 0},
	{Caixa: 0},
	{Partículas: 0},
	{Chave: 0},
	{Sprite2: 0},
	{Senóide: 0},
	{Inimigo: 0},
	{Morteinimigo: 0},
	{Sprite3: 0},
	{PLAY: 0},
	{FundoVitoria: 0},
	{Sprite4: 0},
	{Teclado: 0},
	{Mouse: 0},
	{Sprite5: 0},
	{chaves: 0},
	{coração: 0},
	{vidas: 0},
	{Áudio: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sim: 0},
	{GAMEOver: 0},
	{Texto: 0},
	{Não: 0},
	{NomeDoJogo: 0},
	{Informação: 0},
	{Historia: 0},
	{Texto2: 0},
	{Sprite6: 0},
	{Sprite9: 0},
	{FonteDeSprites: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Historia2: 0},
	{Titulo: 0},
	{Sprite10: 0},
	{Estado: 0},
	{GeraChave: 0},
	{Vidas: 0}
];

self.InstanceType = {
	Chao: class extends self.ITiledBackgroundInstance {},
	Jogador: class extends self.ISpriteInstance {},
	plataforma: class extends self.ITiledBackgroundInstance {},
	PortaSaida: class extends self.ISpriteInstance {},
	portaentrada: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	Chave: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Morteinimigo: class extends self.IParticlesInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	PLAY: class extends self.ISpriteInstance {},
	FundoVitoria: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	chaves: class extends self.ITextInstance {},
	coração: class extends self.ISpriteInstance {},
	vidas: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sim: class extends self.ITextInstance {},
	GAMEOver: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	Não: class extends self.ITextInstance {},
	NomeDoJogo: class extends self.ITextInstance {},
	Informação: class extends self.ISpriteInstance {},
	Historia: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Historia2: class extends self.ITextInstance {},
	Titulo: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {}
}